common: &default_settings
  license_key: '<%= ENV["NEW_RELIC_LICENSE_KEY"] %>'
  app_name: 'Indultometro'
  log_level: info

development:
  <<: *default_settings
  app_name: 'Indultometro (Development)'

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
